CREATE TABLE ItemTypes(
	ItemTypeID int PRIMARY KEY,
	[Name] varchar(50) NOT NULL
)

CREATE TABLE Items(
	ItemID int PRIMARY KEY,
	[Name] varchar(50) NOT NULL,
	ItemTypeID int NOT NULL,
)

CREATE TABLE OrderItems(
	OrderID int UNIQUE NOT NULL,
	ItemID int UNIQUE NOT NULL,
	PRIMARY KEY (OrderID, ItemID)
)

CREATE TABLE Orders(
	OrderID int PRIMARY KEY NOT NULL,
	CustomerID int UNIQUE NOT NULL,
)

CREATE TABLE Cities(
	CityID int PRIMARY KEY NOT NULL,
	[Name] varchar(50) NOT NULL
)

CREATE TABLE Customers(
	CustomerID int PRIMARY KEY NOT NULL,
	[Name] varchar(50) NOT NULL,
	Birthday date NOT NULL,
	CityID int NOT NULL
)

ALTER TABLE Items
	ADD FOREIGN KEY (ItemTypeID) REFERENCES ItemTypes(ItemTypeID)


ALTER TABLE OrderItems
	ADD FOREIGN KEY (ItemID) REFERENCES Items(ItemID)

ALTER TABLE OrderItems
	ADD FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)

ALTER TABLE ORDERS
	ADD UNIQUE (CUSTOMERID)

ALTER TABLE ORDERS
	ADD FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID)

ALTER TABLE CUSTOMERS
	ADD FOREIGN KEY (CITYID) REFERENCES CITIES(CITYID)


	