SELECT FirstName, LastName FROM Employees
WHERE LEFT(FirstName, 2) = 'SA'


SELECT FirstName, LastName FROM Employees
WHERE LastName LIKE '%EI%'

SELECT FirstName FROM Employees
WHERE (DepartmentID = 3 OR DepartmentID = 10) AND (YEAR(HireDate) >= 1995 AND YEAR(HIREDATE)<=2005)

SELECT FirstName, LastName FROM Employees
WHERE JobTitle NOT LIKE '%ENGINEER%' 

SELECT Name FROM TOWNS
WHERE LEN(NAME) = 5 OR LEN(NAME) = 6
ORDER BY NAME 

SELECT TOWNID, NAME FROM Towns
WHERE NAME LIKE 'M%' OR NAME LIKE 'K%' OR NAME LIKE 'B%' OR NAME LIKE 'E%'
ORDER BY Name

SELECT TOWNID, NAME FROM Towns
WHERE NAME NOT LIKE 'R%' AND NAME NOT LIKE 'D%' AND NAME NOT LIKE 'B%'
ORDER BY Name

CREATE VIEW V_EmployeesHiredAfter2000 AS
SELECT FirstName, LastName FROM Employees
WHERE YEAR(HireDate) > 2000

SELECT FirstName, LastName FROM Employees
WHERE LEN(LASTNAME) =5

SELECT  EmployeeID,
		FirstName,
		LastName,
		Salary,
		DENSE_RANK() OVER (PARTITION BY SALARY ORDER BY EMPLOYEEID) AS Rank FROM Employees
		WHERE SALARY BETWEEN 10000 AND 50000
		ORDER BY SALARY DESC

SELECT * FROM Employees
ORDER BY SALARY DESC